Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [4]:
import numpy as np
arr = np.zeros((8,8))
for i in range(0,8):
    for j in range(0,8):
        if i%2 == 0 and j%2 != 0:
            arr[i,j] = 1
        elif i%2 !=0 and j%2 == 0:
            arr[i,j] = 1 
arr = arr.astype(int)
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
