Write a NumPy program to convert a list and tuple into arrays.

In [7]:
import numpy as np
x = np.array([1,2,3,4,5,6,7,8])
print("List to Array:\n", x)
y = np.asarray(((8,4,6),(1,2,3)))
print("Tuple to Array:\n", y)

List to Array:
 [1 2 3 4 5 6 7 8]
Tuple to Array:
 [[8 4 6]
 [1 2 3]]
